export const MAX_PLAYERS_PER_MATCH = 4;
export const DEFAULT_STOCK_COUNT = 3;
export const DEFAULT_STAGE_ID = "rooftop";
export const DEFAULT_GRAVITY_PER_TICK = 1.2;
export const DEFAULT_JUMP_VELOCITY = -14;
export const DEFAULT_ATTACK_DAMAGE = 12;
export const DEFAULT_ATTACK_RANGE = 88;
export const DEFAULT_ATTACK_HEIGHT = 36;
export const DEFAULT_ATTACK_LAUNCH_ANGLE_DEGREES = 16;
export const DEFAULT_ATTACK_BASE_KNOCKBACK = 9;
export const DEFAULT_ATTACK_KNOCKBACK_GROWTH = 0.75;
export const DEFAULT_HITSTUN_TICKS = 8;
export const DEFAULT_ATTACK_COOLDOWN_TICKS = 10;
export const DEFAULT_SPECIAL_DAMAGE = DEFAULT_ATTACK_DAMAGE;
export const DEFAULT_SPECIAL_RANGE = DEFAULT_ATTACK_RANGE;
export const DEFAULT_SPECIAL_HEIGHT = DEFAULT_ATTACK_HEIGHT;
export const DEFAULT_SPECIAL_LAUNCH_ANGLE_DEGREES = DEFAULT_ATTACK_LAUNCH_ANGLE_DEGREES;
export const DEFAULT_SPECIAL_BASE_KNOCKBACK = DEFAULT_ATTACK_BASE_KNOCKBACK;
export const DEFAULT_SPECIAL_KNOCKBACK_GROWTH = DEFAULT_ATTACK_KNOCKBACK_GROWTH;
export const DEFAULT_SPECIAL_HITSTUN_TICKS = DEFAULT_HITSTUN_TICKS;
export const DEFAULT_SPECIAL_COOLDOWN_TICKS = 20;
export const DEFAULT_SPECIAL_CHARGE_MAX_MS = 1000;
export const DEFAULT_SPECIAL_MIN_DAMAGE_MULTIPLIER = 1;
export const DEFAULT_SPECIAL_MAX_DAMAGE_MULTIPLIER = 2;
export const DEFAULT_SPECIAL_MIN_KNOCKBACK_MULTIPLIER = 1;
export const DEFAULT_SPECIAL_MAX_KNOCKBACK_MULTIPLIER = 2;
export const DEFAULT_KO_FALL_SPEED_PER_TICK = 30;
export const DEFAULT_KICK_DAMAGE = 14;
export const DEFAULT_KICK_RANGE = 104;
export const DEFAULT_KICK_HEIGHT = 34;
export const DEFAULT_KICK_LAUNCH_ANGLE_DEGREES = 12;
export const DEFAULT_KICK_BASE_KNOCKBACK = 13;
export const DEFAULT_KICK_KNOCKBACK_GROWTH = 0.9;
export const DEFAULT_KICK_HITSTUN_TICKS = 10;
export const DEFAULT_KICK_COOLDOWN_TICKS = 20;

export const PLAYER_ACTIONS = {
  IDLE: "idle",
  RUN: "run",
  JUMP: "jump",
  FALL: "fall",
  ATTACK: "attack",
  HITSTUN: "hitstun",
  RESPAWN: "respawn",
  KO: "ko",
  KICK: "kick",
} as const;

export type PlayerAction =
  (typeof PLAYER_ACTIONS)[keyof typeof PLAYER_ACTIONS];
